name: Publish Docker Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    needs: test
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        name: Check out code

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: push
    container:
      image: docker.io/bitnami/kubectl:1.29.0
    steps:
      - name: "Patch Image"
        run: |
          echo $KUBE_CONFIG | base64 -d > kc.yaml
          kubectl --kubeconfig kc.yaml set image deployment/gliderbot svc=$NEW_IMAGE
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          NEW_IMAGE: ${{ needs.push.outputs.tag }}
